// @generated by protoc-gen-es v1.0.0
// @generated from file proto/webrtc_signalling.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message ClientSignallingMsg
 */
export declare class ClientSignallingMsg extends Message<ClientSignallingMsg> {
  /**
   * @generated from oneof ClientSignallingMsg.content
   */
  content:
    | {
        /**
         * @generated from field: bytes join = 1;
         */
        value: Uint8Array;
        case: "join";
      }
    | {
        /**
         * @generated from field: Payload.Empty leave = 2;
         */
        value: Payload_Empty;
        case: "leave";
      }
    | {
        /**
         * @generated from field: bytes updatePeerMetadata = 3;
         */
        value: Uint8Array;
        case: "updatePeerMetadata";
      }
    | {
        /**
         * @generated from field: Payload.TrackWithMetadata updateTrackMetadata = 4;
         */
        value: Payload_TrackWithMetadata;
        case: "updateTrackMetadata";
      }
    | {
        /**
         * @generated from field: Payload.Empty renegotiateTracks = 5;
         */
        value: Payload_Empty;
        case: "renegotiateTracks";
      }
    | {
        /**
         * @generated from field: Payload.ICECandidate candidate = 9;
         */
        value: Payload_ICECandidate;
        case: "candidate";
      }
    | {
        /**
         * @generated from field: Payload.SdpOffer sdpOffer = 10;
         */
        value: Payload_SdpOffer;
        case: "sdpOffer";
      }
    | {
        /**
         * @generated from field: Payload.TrackVariant setTargetVariant = 11;
         */
        value: Payload_TrackVariant;
        case: "setTargetVariant";
      }
    | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<ClientSignallingMsg>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ClientSignallingMsg";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): ClientSignallingMsg;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): ClientSignallingMsg;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): ClientSignallingMsg;

  static equals(
    a: ClientSignallingMsg | PlainMessage<ClientSignallingMsg> | undefined,
    b: ClientSignallingMsg | PlainMessage<ClientSignallingMsg> | undefined
  ): boolean;
}

/**
 * @generated from message ServerSignallingMsg
 */
export declare class ServerSignallingMsg extends Message<ServerSignallingMsg> {
  /**
   * @generated from oneof ServerSignallingMsg.content
   */
  content:
    | {
        /**
         * Contains peer_id
         *
         * @generated from field: string peerAccepted = 1;
         */
        value: string;
        case: "peerAccepted";
      }
    | {
        /**
         * @generated from field: Payload.Peer peerJoined = 2;
         */
        value: Payload_Peer;
        case: "peerJoined";
      }
    | {
        /**
         * Contains id of leaving peer
         *
         * @generated from field: string peerLeft = 3;
         */
        value: string;
        case: "peerLeft";
      }
    | {
        /**
         * @generated from field: Payload.Track trackAdded = 4;
         */
        value: Payload_Track;
        case: "trackAdded";
      }
    | {
        /**
         * Id of removed track
         *
         * @generated from field: string trackRemoved = 5;
         */
        value: string;
        case: "trackRemoved";
      }
    | {
        /**
         * @generated from field: Payload.TrackVariant variantSwitched = 6;
         */
        value: Payload_TrackVariant;
        case: "variantSwitched";
      }
    | {
        /**
         * @generated from field: Payload.SdpAnswer sdpAnswer = 7;
         */
        value: Payload_SdpAnswer;
        case: "sdpAnswer";
      }
    | {
        /**
         * @generated from field: Payload.OfferData offerData = 8;
         */
        value: Payload_OfferData;
        case: "offerData";
      }
    | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<ServerSignallingMsg>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "ServerSignallingMsg";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): ServerSignallingMsg;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): ServerSignallingMsg;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): ServerSignallingMsg;

  static equals(
    a: ServerSignallingMsg | PlainMessage<ServerSignallingMsg> | undefined,
    b: ServerSignallingMsg | PlainMessage<ServerSignallingMsg> | undefined
  ): boolean;
}

/**
 * @generated from message Payload
 */
export declare class Payload extends Message<Payload> {
  constructor(data?: PartialMessage<Payload>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Payload";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): Payload;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): Payload;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): Payload;

  static equals(
    a: Payload | PlainMessage<Payload> | undefined,
    b: Payload | PlainMessage<Payload> | undefined
  ): boolean;
}

/**
 * @generated from message Payload.Empty
 */
export declare class Payload_Empty extends Message<Payload_Empty> {
  constructor(data?: PartialMessage<Payload_Empty>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Payload.Empty";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): Payload_Empty;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): Payload_Empty;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): Payload_Empty;

  static equals(
    a: Payload_Empty | PlainMessage<Payload_Empty> | undefined,
    b: Payload_Empty | PlainMessage<Payload_Empty> | undefined
  ): boolean;
}

/**
 * @generated from message Payload.TrackWithMetadata
 */
export declare class Payload_TrackWithMetadata extends Message<Payload_TrackWithMetadata> {
  /**
   * @generated from field: string trackId = 2;
   */
  trackId: string;

  /**
   * @generated from field: bytes metadata = 3;
   */
  metadata: Uint8Array;

  constructor(data?: PartialMessage<Payload_TrackWithMetadata>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Payload.TrackWithMetadata";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): Payload_TrackWithMetadata;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): Payload_TrackWithMetadata;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): Payload_TrackWithMetadata;

  static equals(
    a:
      | Payload_TrackWithMetadata
      | PlainMessage<Payload_TrackWithMetadata>
      | undefined,
    b:
      | Payload_TrackWithMetadata
      | PlainMessage<Payload_TrackWithMetadata>
      | undefined
  ): boolean;
}

/**
 * @generated from message Payload.Track
 */
export declare class Payload_Track extends Message<Payload_Track> {
  /**
   * @generated from field: string owner = 1;
   */
  owner: string;

  /**
   * @generated from field: string trackId = 2;
   */
  trackId: string;

  /**
   * @generated from field: bytes metadata = 3;
   */
  metadata: Uint8Array;

  /**
   * @generated from field: string mid = 4;
   */
  mid: string;

  constructor(data?: PartialMessage<Payload_Track>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Payload.Track";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): Payload_Track;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): Payload_Track;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): Payload_Track;

  static equals(
    a: Payload_Track | PlainMessage<Payload_Track> | undefined,
    b: Payload_Track | PlainMessage<Payload_Track> | undefined
  ): boolean;
}

/**
 * @generated from message Payload.ICECandidate
 */
export declare class Payload_ICECandidate extends Message<Payload_ICECandidate> {
  /**
   * @generated from field: string candidate = 1;
   */
  candidate: string;

  /**
   * @generated from field: uint64 mLineIndex = 2;
   */
  mLineIndex: bigint;

  constructor(data?: PartialMessage<Payload_ICECandidate>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Payload.ICECandidate";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): Payload_ICECandidate;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): Payload_ICECandidate;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): Payload_ICECandidate;

  static equals(
    a: Payload_ICECandidate | PlainMessage<Payload_ICECandidate> | undefined,
    b: Payload_ICECandidate | PlainMessage<Payload_ICECandidate> | undefined
  ): boolean;
}

/**
 * @generated from message Payload.SdpOffer
 */
export declare class Payload_SdpOffer extends Message<Payload_SdpOffer> {
  /**
   * @generated from field: string sdp = 1;
   */
  sdp: string;

  /**
   * @generated from field: repeated Payload.Track tracks = 2;
   */
  tracks: Payload_Track[];

  constructor(data?: PartialMessage<Payload_SdpOffer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Payload.SdpOffer";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): Payload_SdpOffer;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): Payload_SdpOffer;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): Payload_SdpOffer;

  static equals(
    a: Payload_SdpOffer | PlainMessage<Payload_SdpOffer> | undefined,
    b: Payload_SdpOffer | PlainMessage<Payload_SdpOffer> | undefined
  ): boolean;
}

/**
 * @generated from message Payload.SdpAnswer
 */
export declare class Payload_SdpAnswer extends Message<Payload_SdpAnswer> {
  /**
   * @generated from field: string sdp = 1;
   */
  sdp: string;

  /**
   * @generated from field: map<string, string> midToTrackId = 2;
   */
  midToTrackId: { [key: string]: string };

  constructor(data?: PartialMessage<Payload_SdpAnswer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Payload.SdpAnswer";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): Payload_SdpAnswer;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): Payload_SdpAnswer;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): Payload_SdpAnswer;

  static equals(
    a: Payload_SdpAnswer | PlainMessage<Payload_SdpAnswer> | undefined,
    b: Payload_SdpAnswer | PlainMessage<Payload_SdpAnswer> | undefined
  ): boolean;
}

/**
 * @generated from message Payload.TrackVariant
 */
export declare class Payload_TrackVariant extends Message<Payload_TrackVariant> {
  /**
   * @generated from field: string trackId = 1;
   */
  trackId: string;

  /**
   * @generated from field: string variant = 2;
   */
  variant: string;

  constructor(data?: PartialMessage<Payload_TrackVariant>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Payload.TrackVariant";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): Payload_TrackVariant;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): Payload_TrackVariant;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): Payload_TrackVariant;

  static equals(
    a: Payload_TrackVariant | PlainMessage<Payload_TrackVariant> | undefined,
    b: Payload_TrackVariant | PlainMessage<Payload_TrackVariant> | undefined
  ): boolean;
}

/**
 * @generated from message Payload.TrackVariantSwitched
 */
export declare class Payload_TrackVariantSwitched extends Message<Payload_TrackVariantSwitched> {
  /**
   * @generated from field: Payload.TrackVariant newVariant = 1;
   */
  newVariant?: Payload_TrackVariant;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;

  constructor(data?: PartialMessage<Payload_TrackVariantSwitched>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Payload.TrackVariantSwitched";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): Payload_TrackVariantSwitched;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): Payload_TrackVariantSwitched;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): Payload_TrackVariantSwitched;

  static equals(
    a:
      | Payload_TrackVariantSwitched
      | PlainMessage<Payload_TrackVariantSwitched>
      | undefined,
    b:
      | Payload_TrackVariantSwitched
      | PlainMessage<Payload_TrackVariantSwitched>
      | undefined
  ): boolean;
}

/**
 * @generated from message Payload.OfferData
 */
export declare class Payload_OfferData extends Message<Payload_OfferData> {
  /**
   * @generated from field: uint32 audioTracks = 1;
   */
  audioTracks: number;

  /**
   * @generated from field: uint32 videoTracks = 2;
   */
  videoTracks: number;

  /**
   * @generated from field: repeated Payload.OfferData.TurnServer integratedTurnServers = 3;
   */
  integratedTurnServers: Payload_OfferData_TurnServer[];

  constructor(data?: PartialMessage<Payload_OfferData>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Payload.OfferData";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): Payload_OfferData;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): Payload_OfferData;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): Payload_OfferData;

  static equals(
    a: Payload_OfferData | PlainMessage<Payload_OfferData> | undefined,
    b: Payload_OfferData | PlainMessage<Payload_OfferData> | undefined
  ): boolean;
}

/**
 * @generated from message Payload.OfferData.TurnServer
 */
export declare class Payload_OfferData_TurnServer extends Message<Payload_OfferData_TurnServer> {
  /**
   * @generated from field: string addr = 1;
   */
  addr: string;

  /**
   * @generated from field: uint32 port = 2;
   */
  port: number;

  /**
   * @generated from field: string transport = 3;
   */
  transport: string;

  /**
   * @generated from field: string password = 4;
   */
  password: string;

  /**
   * @generated from field: string username = 5;
   */
  username: string;

  constructor(data?: PartialMessage<Payload_OfferData_TurnServer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Payload.OfferData.TurnServer";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): Payload_OfferData_TurnServer;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): Payload_OfferData_TurnServer;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): Payload_OfferData_TurnServer;

  static equals(
    a:
      | Payload_OfferData_TurnServer
      | PlainMessage<Payload_OfferData_TurnServer>
      | undefined,
    b:
      | Payload_OfferData_TurnServer
      | PlainMessage<Payload_OfferData_TurnServer>
      | undefined
  ): boolean;
}

/**
 * @generated from message Payload.Peer
 */
export declare class Payload_Peer extends Message<Payload_Peer> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: bytes metadata = 2;
   */
  metadata: Uint8Array;

  constructor(data?: PartialMessage<Payload_Peer>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "Payload.Peer";
  static readonly fields: FieldList;

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>
  ): Payload_Peer;

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>
  ): Payload_Peer;

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>
  ): Payload_Peer;

  static equals(
    a: Payload_Peer | PlainMessage<Payload_Peer> | undefined,
    b: Payload_Peer | PlainMessage<Payload_Peer> | undefined
  ): boolean;
}
